main: cc.carm.plugin.quickshopcracker.Main
name: QuickShop-Hikari-Cracker
version: ${project.version}
author: CarmJos
website: ${project.url}
description: ${project.description}

api-version: 1.18

loadbefore:
  - QuickShop-Hikari
